name: mentora_online_courses_app
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter



flutter_native_splash:
  color: "#FEF7FF"   # Color of the background of the splash screen 
  image: assets/master/splash_screen.png  # image path
  android_12:
    image: assets/master/splash_screen.png  # image path
    color: "#FEF7FF"   # Color of the background of the splash screen 



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/master/icon.png"  # Logo image path 
  min_sdk_android: 21




flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/



  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
